In machine Learning we provide outcomes for the model to learn and the model will extract the features that will help it understand the task and perform the action.

X - represents our feature matrix 
y - represents our target output

ML Development process

- Understand the business problem
- Decide if ML is the right tool to do the job
- Understand the data, its reliablity 
- Prepare the data [Cleaning and building a pipline to convert it to a tabluar form]
- Modeling - select the best model taht works for you and fitting it to our need
- Evalauation - accuracy and precision and other factors
- Deployment

Multiple comparisons problem (also called the multiplicity problem), It states: when you test many hypotheses (or check many validation splits, features, or models), the chance of seeing a “significant” result by random chance increases. That makes the observed performance in training/validation look better than the true generalization.

## Numpy Integration

In [1]:
import numpy as np 

Single Dimension Array

In [2]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.full(10,5.4)

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

In [4]:
# From array to np

my_np_array = np.array([12,3,4,54,6])

my_np_array

array([12,  3,  4, 54,  6])

In [6]:
my_range = np.arange(1,11,2)

my_range

array([1, 3, 5, 7, 9])

In [7]:
my_lin_space = np.linspace(1,10,3)
my_lin_space

array([ 1. ,  5.5, 10. ])

Multi Dimensional arrays

In [9]:
# Two dimensions

two_dim_ar = np.array([[1,2],[3,4]])
print(two_dim_ar,two_dim_ar.shape, two_dim_ar[0,1])

[[1 2]
 [3 4]] (2, 2) 2


In [5]:
# Multi dimensional arrays

multi_dim = np.array([[[1,2,3],[4,5,6],[6,7,8]]])

multi_dim, multi_dim.shape, multi_dim.ndim

(array([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]]),
 (1, 3, 3),
 3)

In [12]:
# Getting elements with row and columns

# With row

multi_dim[:,1,:]

# Getting columns
multi_dim[:,:,1]

array([[2, 5, 7]])

In [12]:
# Working with random values
random_value = np.random.seed(2)
random_value = np.random.rand(3,4)
random_value

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239],
       [0.4203678 , 0.33033482, 0.20464863, 0.61927097],
       [0.29965467, 0.26682728, 0.62113383, 0.52914209]])

In [14]:
random_int = np.random.randint(low=3,high=40,size=(3,4))
random_int

array([[ 6,  7, 36,  6],
       [ 8, 27,  7,  9],
       [34, 22, 34,  5]])

In [15]:
a = np.arange(5)

b = np.random.randint(1,5, size=(5))

a[a>b]


array([2, 3, 4])

In [19]:
a.min()
a.sum()
a.sort()

## Linear Algebra

In [25]:
my_arr = np.array([2,3,4,5])

my_sec = np.array([3,4,5,6])


np.matmul(my_arr,my_sec)

np.int64(68)